// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfiettgrvdkmwxazfoli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmaWV0dGdydmRrbXd4YXpmb2xpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2MzQ0OTksImV4cCI6MjA4ODIxMDQ5OX0.bZMPO4V1ypPN6ck7mXYqa0SZbj1cwg2SUqBz2vXSptM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});