// This file is automatically generated. Do not edit it directly.
// Import the Supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
//
// The actual client is created in "@/lib/supabase" using environment variables.

export { supabase } from "@/lib/supabase";